# Select the appropriate Docker Compose version
version: '3.9'
# Define the services to be run
services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://abdullah:postgres@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:latest:alpine
    environment:
      POSTGRES_USER: abdullah
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  postgres_data: