version: '3.8'
services:
  fastapi_app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
      - redis
    environment:
      DATABASE_URL: postgresql://user:password@postgres_db:5432/mydatabase

  redis:
    image: redis:7

  celery:
    build: .
    command: celery -A app.celery.celery_app worker --loglevel=info
    depends_on:
      - redis
      - postgres_db
    volumes:
      - ./app:/app/app

  celery-beat:
    build: .
    command: celery -A app.celery.celery_app beat --loglevel=info
    depends_on:
      - redis
      - postgres_db
    volumes:
      - ./app:/app/app

  postgres_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: